import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import RootLayoutWrapper from "@/components/layout_wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="zh-CN">
        <body>
          <AntdRegistry>
            <RootLayoutWrapper>{children}</RootLayoutWrapper>
          </AntdRegistry>
        </body>
      </html>
    </>
  );
}
